---
abstract: 'Importing XML::Reader using XML::Parser'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Reader-RS
provides:
  XML::Reader::RS:
    file: lib/XML/Reader/RS.pm
    version: 0.01
requires:
  XML::Parser: 0
  XML::Reader: 0.47
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
